import json
import time
from pathlib import Path
from typing import Optional

import numpy as np
from PIL import Image

try:
    import tensorflow as tf
except Exception:  # pragma: no cover
    tf = None


def _find_json(root: Path, names: tuple[str, ...]) -> Optional[Path]:
    for name in names:
        for p in root.rglob(name):
            if p.is_file():
                return p
    return None


def _labels_from_json(path: Path, expected: int) -> Optional[list[str]]:
    try:
        obj = json.loads(path.read_text(encoding='utf-8'))
        if isinstance(obj, dict):
            pairs = []
            for k, v in obj.items():
                try:
                    pairs.append((int(k), str(v)))
                except Exception:
                    try:
                        pairs.append((int(v), str(k)))
                    except Exception:
                        continue
            pairs.sort()
            labels = [v for _, v in pairs]
            if len(labels) == expected and all(labels):
                return labels
    except Exception:
        return None
    return None


def _discover_labels(root: Path, expected: int, model_kind: str) -> list[str]:
    preferred = []
    if model_kind == 'm1':
        preferred = ['model1_crop_mapping.json', 'm1_mapping.json', 'class_indices_m1.json']
    elif model_kind == 'm2':
        preferred = ['model2_disease_mapping.json', 'm2_mapping.json', 'class_indices_m2.json']

    p = _find_json(root, tuple(preferred))
    if p:
        labels = _labels_from_json(p, expected)
        if labels:
            return labels

    # Search CSV manifests generated by the training pipeline.
    try:
        import csv
        for p in root.rglob('*.csv'):
            n = p.name.lower()
            if model_kind not in n and not ('manifest' in n or 'train' in n or 'val' in n or 'test' in n):
                continue
            with p.open('r', encoding='utf-8', errors='ignore', newline='') as f:
                reader = csv.DictReader(f)
                if not reader.fieldnames or 'label' not in reader.fieldnames:
                    continue
                vals = sorted({str(r['label']) for r in reader if r.get('label') is not None})
                if len(vals) == expected:
                    return vals
    except Exception:
        pass

    # Finally, search train directories for an exact class-count match.
    candidate_roots = []
    if model_kind == 'm1':
        candidate_roots += [root / 'datasets', root / 'edge_ml']
    else:
        candidate_roots += [root / 'datasets', root / 'edge_ml']

    seen = set()
    for base in candidate_roots:
        if not base.exists():
            continue
        for p in base.rglob('*'):
            if not p.is_dir() or p in seen:
                continue
            try:
                children = sorted(x.name for x in p.iterdir() if x.is_dir() and not x.name.startswith('.'))
            except Exception:
                continue
            if len(children) == expected and all(children):
                seen.add(p)
                return children

    return [f'class_{i}' for i in range(expected)]


class KerasClassifier:
    def __init__(self, name: str, model_path: Path, root: Path, model_kind: str):
        self.name = name
        self.model_path = Path(model_path)
        self.root = Path(root)
        self.model_kind = model_kind
        self.model = None
        self.labels: list[str] = []
        self.input_size = (224, 224)
        self.load_error = None

        if tf is None:
            self.load_error = 'TensorFlow is not installed.'
            return
        if not self.model_path.exists():
            self.load_error = f'Model not found: {self.model_path}'
            return
        try:
            self.model = tf.keras.models.load_model(str(self.model_path), compile=False)
            shape = self.model.input_shape
            if isinstance(shape, tuple) and len(shape) == 4 and shape[1] and shape[2]:
                self.input_size = (int(shape[1]), int(shape[2]))
            out_shape = self.model.output_shape
            expected = int(out_shape[-1])
            self.labels = _discover_labels(self.root, expected, model_kind)
            self._warmup()
        except Exception as exc:
            self.load_error = f'{type(exc).__name__}: {exc}'
            self.model = None

    @property
    def loaded(self) -> bool:
        return self.model is not None

    def _warmup(self):
        dummy = np.zeros((1, *self.input_size, 3), dtype=np.float32)
        self.model.predict(dummy, verbose=0)

    def predict(self, image: Image.Image) -> dict:
        if not self.loaded:
            raise RuntimeError(self.load_error or 'Model not loaded')
        t0 = time.perf_counter()
        img = image.convert('RGB').resize(self.input_size, Image.LANCZOS)
        arr = np.asarray(img, dtype=np.float32) / 255.0
        probs = self.model.predict(arr[None, ...], verbose=0)[0]
        idx = int(np.argmax(probs))
        conf = float(probs[idx])
        label = self.labels[idx] if idx < len(self.labels) else f'class_{idx}'
        top_idx = np.argsort(probs)[::-1][:3]
        top3 = [
            {'class_id': int(i), 'class_name': self.labels[int(i)] if int(i) < len(self.labels) else f'class_{int(i)}', 'confidence': round(float(probs[int(i)]), 6)}
            for i in top_idx
        ]
        return {
            'model': self.name,
            'class_id': idx,
            'class_name': label,
            'confidence': round(conf, 6),
            'top3': top3,
            'input_size': list(self.input_size),
            'processing_time_ms': round((time.perf_counter() - t0) * 1000, 2),
        }
